spring:
  datasource:
    url: jdbc:mysql://10.189.108.57:3306/vip_solr_bi?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: vdptest
    password: vdptest
    driver-class-name: com.mysql.jdbc.Driver

